# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: npm install selenium # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: python Lembdatest certification.py
    
